name: Build

on:
  push:
    paths:
      - 'src/**'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'src/**'
  workflow_dispatch:

jobs:
  dotnet:
    name: .NET Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore src/AkaMoney.sln

    - name: Build
      run: dotnet build src/AkaMoney.sln --no-restore --configuration Release
  vue:
    name: Vue.js Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: 'src/akamoney-frontend/package-lock.json'

    - name: Install dependencies
      working-directory: ./src/akamoney-frontend
      run: npm ci

    - name: Lint
      working-directory: ./src/akamoney-frontend
      run: npm run lint

    - name: Build
      working-directory: ./src/akamoney-frontend
      run: npm run build
